
spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-name: Google
#            client-id: 785216230516-1h8hoagkginolldjirvtgiebidmqe38i.apps.googleusercontent.com
#            client-secret: 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
#            authorization-grant-type: authorization_code
#            scope : email


  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/healthone
    username: root
    password: ssafy
  jpa:
#    hibernate:
#      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  server:
    port: 80
springboot:
  jwt:
    secret: 8q2ht89sbguniuqt9ieg